# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'crush' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for crush
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git', :branch => 'master'

  target 'crushTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'crushUITests' do
    # Pods for testing
  end

end
